<?php

$lang=array(
'liv' => 'Free delivery at 300DH of purchases',
'fran' => 'Frensh',
'ang' => 'English',
'arb' => 'Arab',
'one' => 'Home ',
'two' => 'Shop',
'pages' => 'Pages',
'details' => 'Shop details',
'panier' => 'Shoping Cart',
'checkout' => 'chek Out',
'blogdet' => 'blog details',
'blog' => 'Blog',
'contact' => 'Contact',
'conn' => 'Login',
'ins' => 'register',
'addition' => 'Total',
'dh' => 'dh',
'menu' => 'menu',
'poissf' => 'FRESH FISH',
'homard' => 'LOBSTER',
'fruits' => 'SEAFOOD',
'epecerie' => 'GROCERY OF THE SEA',
'poissn' => 'CLEANED FISH',
'pret' => 'READY TO COOK',
'rech' => 'SEARCH',
'poisss' => 'FISH',
'ultra' => 'ULTRA FRESH',
'livex' => 'Express delivery available',
'dec' => 'Discover',
'prodp' => 'Popular Products',

'crev' => 'Shrimp',
'crevr' => 'Royal Shrimp',
'moule' => 'Mussel',
'raie' => 'Line',
'sardin' => 'Sardin',
'merlan' => 'Whiting ',
'calamar' => 'Squid',
'couteaux' => 'Couteaux',
'huitres' => 'Oysters',
'langouste' => 'Lobster',
'homardr' => 'Royal Lobster',
'saumon' => 'Filleted Salmon',
'espd' => 'Swordfish ',
'loup' => 'Loup bar entier',
'merlanc' => 'Merlan colin entier',
'pag' =>'Royal Pageot à la Pièce ',
'palourde' => 'Clam',
'truite' => 'Trout',
'sole' => 'Sole peeled beach',
'calamarf' => 'Calamar en feuilles',
'ombrine' => 'Ombrine in Darnes',
'mostelle' => 'Mostelle Skinless Fillet',

'act' => 'NEWS',
'dblog' => 'From the blog',
'dernp' => 'Last products',
'kg' => 'kg',
'promo' => 'Promotions',
'contacter' => 'Contact us',
'tel' => 'Phone',
'add' => 'Adresse',
'hor' => 'Timetable',
'email' => 'Email',
'msg' => 'Send us a message',
'env' => 'Send'
);




?>